note = {
  "hpd": ["gg", "a", "g", "c", "b", "-", "-", "-", "gg", "a", "g", "d", "c", "-", "-", "-", "gg", "e", "d", "c",
    "b", "a", "-", "-", "ee", "d", "c", "d", "c", "-", "-", "-"
  ],
  "lilbrownjug": [
    "ac", "c", "cb", "dd", "ee", "de", "fg", "a",
    "ac", "c", "cb", "dd", "ee", "de", "af", "f"
  ],
  "sakura": ["a", "a", "b", "-", "a", "a", "b", "-", "a", "b", "c", "b", "a",
    "ba", "f", "-", "e", "c", "e", "f", "e", "ec", "b", "-", "a", "a", "b", "-", "a", "a", "b", "-", "e", "f",
    "ba",
    "f", "e", "-", "-", "-"
  ],
  "gingle": ["e", "e", "e", "-",
    "e", "e", "e", "-",
    "e", "g", "c", "d",
    "e", "-", "-", "-",
    "f", "f", "f", "-",
    "e", "e", "e", "-",
    "d", "d", "d", "e",
    "d", "-", "g", "-",
    "g", "g", "g", "-",
    "e", "-", "d", "-",
    "c", "-", "a", "-",
    "a", "a", "a", "-",
    "f", "-", "e", "-"
  ],
  "ogreenland": ["de", "ga", "bg", "b", "a", "fa", "ga", "eg", "de", "ga", "bg", "bd", "cb", "ag", "g", "g",
    "bcc",
    "ba", "bc", "d", "cb", "ag", "ab", "c", "bcc", "ba", "bc", "d", "cb", "ag", "g", "g"
  ],
  "janenahi": ["-e", "fg",
    "c",
    "-", "-e", "fg",
    "c",
    "-", "-e", "fg",
    "c",
    "-f", "e", "d", "-", "-", "ed", "ed", "-c", "-", "e", "d", "ed", "eg", "f", "e", "c", "g", "e", "d", "ed",
    "eg",
    "f", "e", "c", "g", "e", "d", "ed", "eg", "f", "e", "c", "ce", "d", "-", "-", "-"
  ],
  "twinkle": ["c", "c", "g", "g",
    "a", "a", "g", "-",
    "f", "f", "e", "e",
    "d", "d", "c", "-",
    "g", "g", "f", "f",
    "e", "e", "d", "-",
    "g", "g", "f", "e",
    "ef", "de", "c", "-"
  ],
  "flowerofedinburgh": ["-", "-", "-", "ca", "g", "ga", "c", "cd", "ec", "eg", "fe", "dc", "bc", "ab", "ga", "bc",
    "db", "gb", "a", "ca", "g", "ga", "c", "cd", "ec", "eg", "ab", "ca", "gf", "ed", "cb", "cd", "e", "c", "c", "gab",
    "c", "cb", "ce", "dc", "b", "bg", "bd", "cb", "ag", "ab", "cb", "ag", "e", "a", "a", "cba", "ge", "ce", "g", "efg", "ag", "ab", "c", "ba", "gf", "ed", "cb", "cd", "e", "c", "c", "-"
  ],
  "ntc": ["a", "e", "d", "e",
    "c", "d", "c", "b",
    "a", "e", "d", "e",
    "cd", "eg", "d", "-",
    "g", "g", "g", "e",
    "a", "g", "e", "d",
    "de", "dc", "d-", "cb",
    "d", "c", "b", "a"
  ],
  "temp": ["c", "d", "e", "f", "g", "a", "b", "c", "cd", "de", "ef", "fg", "ga", "ab", "bc", "-", "cde", "def", "efg", "gab", "abc", "cdef", "defg", "efga", "fgab"],
  "aroundstupa": ["-", "-", "-", "-", "-", "f", "e", "d", "e", "f", "g", "f", "g", "g", "-", "ga", "a#", "a", "g",
    "f", "-", "gf",
    "d#", "d", "c", "a#", "c", "f", "-", "d#", "d", "c", "-", "-", "-", "-", "f", "-", "e", "f", "g", "b", "b",
    "c",
    "-", "c", "-", "f", "f", "-", "e", "d", "c", "-", "b", "-", "b", "c", "d#", "d", "c", "-", "-", "-", "b",
    "-",
    "c", "-", "b", "c", "-", "a", "g", "a", "f", "g", "-", "-", "b", "-", "c", "ed", "c", "b", "-", "a", "g",
    "a",
    "g", "-", "-", "-"
  ],
  "afreen": ["cb", "agg", "d-d", "d", "bc", "de", "dg", "fe", "cb", "ce", "ee", "ef", "ed", "dg", "fe", "-", "cb", "c", "ce", "ee", "ef", "ed", "dg", "fe", "ef", "ed", "da", "aa", "a", "ff", "a", "gg", "ef", "ed", "da", "ac", "agf", "a", "gg", "-", "gg", "g", "b", "c", "ba", "ff", "a", "gg", "gg", "cc", "c", "c", "cdb", "cc", "c", "c",
    "bb", "bd", "b", "a", "a", "ff", "gf", "d", "bab", "ce", "f", "ed", "ab", "cc", "b", "c"
  ],
  "wochugalli": ["G", "GB", "B", "B", "G", "GB", "B", "B", "A", "B", "C", "C", "B", "BA", "G", "-", "G", "GA", "G", "f", "e", "ed", "c", "b", "-", "bc", "-d", "e", "f#", "f#", "g", "-", "-", "bd", "-c", "b", "a", "af", "g", "g", "f#", "fe", "d", "c", "d", "f#", "g", "-", "-", "de", "-g", "g", "ga", "g", "f#", "ga", "ag", "a#", "a", "g", "f", "e", "-", "-", "de", "-g", "f", "e", "ed", "c", "b", "-", "bc", "-d", "e", "f#", "f#", "g", "-", "d", "d", "f", "f", "g", "g", "ad", "ba", "ba", "ag", "a", "gf", "g", "-", "-", "ed", "fgf", "dc", "df", "g"],
  "jigubaisha": ["c", "ce", "cb", "c", "cb", "ce", "cb", "c",
    "g", "f", "e", "d", "c",
    "gg", "ff", "e",
    "cc", "ce", "ef", "dd", "cc", "gg", "ff", "e",
    "-", "-", "-", "-", "a", "ga", "gf", "ff", "ff", "d ", "edc ", "bc ", "e", "d", "ed", "cb",
    "c", "ba", "ga", "ba", "ga", "b", "a", "b", "c", "g", "ag", "e", "f", "c", "-", "b", "a",
    "g", "ag", "f", "e", "f", "g", "-", "-", "gg",
    "f", "e", "d", "ee", "db", "c", "def", "gg", "ff", "ee", "dgf", "ee", "db", "c", "-",
    "ee", "fg", "fe", "ee", "ee", "fg", "fe", "e", "dd", "dd", "dd", "ef", "gg", "ffe", "e", "-ga",
    "ccb", "ag", "gaga", "g-ga", "ccb", "ag", "gab", "ce", "ee", "fg", "fe", "ee", "ee", "fg", "fe",
    "e", "-", "-", "-", "dd", "dd", "dd", "ef", "gg", "ffe", "e", "-a", "gag", "f", "ff", "f", "ff", "f", "-f", "ed", "e", "-", "-", "-", "-", "-", "-", "-"
  ],
  "tknt": ["-cd", "edc", "cg", "-", "-", "-g", "dd", "dc", "c", "edc", "cg", "-", "-", "-g", "dd", "dc", "c-cd", "edc", "", "cg", "-cd", "dd", "-", "-", "eg", "e", "dc-c", "-", "-", "-", "def", "-", "-", "-", "-", "-", "-dd", "-dd", "d-ba", "aa-", "aa", "a-gg", "gd", "e-gg", "ge", "e", "ge-g", "e", "gga", "cd", "-", "cd", "edc", "c-c", "e", "c", "g", "ddd", "dd-cd", "edc", "c", "c-g", "eee", "e-ed", "g-d", "e", "ddd", "d-dcd", "edc", "c", "a-a", "aaag", "g-cag", "ga", "ge", "dc", "e", "-", "eg-g", "g-ge", "ed", "d"],
  "jasmineflower": ["e", "eg", "ac", "ca", "g", "ga", "g", "-", "e", "eg", "ac", "ca", "g", "ga", "g", "-", "g", "g", "g", "eg", "a", "ac", "g", "-", "e", "de", "g", "ed", "c", "cd", "c", "-", "ed", "ce", "d", "eg", "a", "ac", "g", "-", "d", "eg", "de", "dc", "g", "-", "g", "e", "d", "-e", "cd", "ca", "g", "-", "-", "-"],
  "riverflowsintoyou": ["eg", "c", "b", "c", "b", "c", "g", "-", "f", "e", "f", "g", "e", "d", "-", "-", "cb", "c", "-", "-g", "cd", "e", "-", "-", "ef", "g", "-", "-", "fe", "d", "-", "-", "eg", "c", "b", "c", "b", "c", "g", "-", "f", "e", "f", "g", "e", "d", "-", "-", "dcb", "c", "-", "-b", "cd", "e", "-", "-", "ef", "g", "-", "-", "efe", "d", "-", "-", "cd", "cb", "c", "g", "cd", "cb", "c", "g", "cd", "cb", "cd", "ef", "ge", "dc", "b", "-", "cd", "cb", "c", "g", "cd", "cb", "c", "g", "cd", "cb", "cd", "ef", "g", "-", "ga", "gf", "ed", "cb", "c", "g", "cd", "cb", "c", "g", "cd", "cb", "cd", "ef", "ge", "dc", "b", "a", "b", "g", "-", "-"],
  "jasnebahara": ["cc", "ded", "ccd", "ag", "cc", "ded", "cc", "a", "c-c", "d", "c-c", "a", "cd", "cd", "cd", "cd", "ce", "de", "dc", "cc", "c", "c", "d", "-", "ce", "de", "dc", "cc", "c", "c", "a", "-", "ac", "cd", "d", "dc", "ac", "cd", "d", "e", "dc", "ag", "g", "-", "-", "-", "-", "-", "ac", "cd", "-e", "-", "ga", "-", "c", "-", "-", "d", "e", "-", "b", "b", "ag", "gg", "g", "g", "a", "-", "ad", "cb", "ag", "gg", "g", "ag", "e", "-", "ef", "g", "g", "a", "a", "ac", "bd", "ba", "ag", "g", "-", "-", "b", "-", "d", "-", "g", "fd", "c", "-", "bc", "ab", "c", "-", "ab", "c", "f", "-", "-", "-", "-gag", "fe", "ed", "ef", "e", "-", "-", "-", "-", "-", "ef", "ga", "a", "a", "ab", "ac", "c", "-", "ef", "ga", "fg", "dc", "bc", "ab", "c", "-", "a", "a", "b", "b", "d", "d", "e", "-", "d", "c", "-", "-", "de", "eee", "de", "eee", "d", "ee", "dcdc", "a-", "gacc", "-", "bdb", "c", "bdb", "c", "bag", "g", "ga", "fg", "-g", "ge", "dc", "-a", "cc", "-"],
  "farewelltoireland": ["d", "-f", "a", "-b", "ca", "ge", "ac", "ge",
    "d", "-f", "a", "-b", "ca", "ge", "ed", "dc",
    "d", "-f", "a", "-b", "ca", "ge", "c", "dc",
    "ag", "ac", "d", "ed", "ca", "ge", "ed", "dc",

    "ad", "-d", "dc", "ab", "c", "cd", "ca", "gc",
    "ad", "-d", "dc", "ab", "ca", "ge", "ed", "-d",
    "dc", "ab", "cd", "ca", "ga", "ge", "cd", "efg",
    "fd", "ed", "efg", "ab", "ca", "ge", "ed", "dc",

    "ad", "ddd", "ad", "ddd", "ga", "ge", "cd", "efg",
    "ad", "ddd", "ad", "db", "ga", "ge", "cd", "efg",
    "ad", "ddd", "ad", "ddd", "ga", "ge", "cd", "efg",
    "fd", "ed", "efg", "ab", "ca", "ge", "ed", "dc",

    "da", "fga", "da", "fga", "cg", "efg", "cg", "efg",
    "da", "fga", "de", "db", "ca", "ge", "ed", "dd",
    "dc", "ab", "cd", "ca", "ga", "ge", "cd", "efg",
    "fd", "ed", "efg", "ab", "ca", "ge", "ed", "dc"
  ],
  "binksake": ["eg", "gg", "-", "ag", "e", "g", "-", "-", "eg", "gg", "-", "ag", "e", "c", "-", "-", "ge", "dc", "ab", "c", "ge", "dc", "ab", "g", "ab", "gg", "ab", "cd", "ee", "dc", "d", "-", "ge", "dc", "ab", "c", "ge", "dc", "ab", "g", "ab", "gg", "ab", "cd", "ec", "dd", "c", "-"],
  "simauta": ["-", "-", "g", "b", "c", "-", "c", "e", "f", "g", "b", "c", "g", "-", "b", "c", "f", "-", "e", "f", "d", "c", "b", "d", "c", "-", "-", "-", "-", "-", "c", "b", "a", "c", "e", "g", "e", "-", "e", "d", "c", "dc", "a", "g", "a", "-", "c", "d", "e", "-", "g", "-", "d", "-", "e", "d", "c", "-", "d", "-", "-", "-", "g", "b", "c", "-", "c", "d", "c", "b", "g", "b", "c", "-", "c", "d", "c", "b", "a", "ag", "f", "-", "f", "g", "d", "g", "b", "d", "c", "-", "-", "-"],
  "prayas": ["ed", "d-c", "-cb", "ab", "dc", "cb", "a-g", "-", "g-e", "dd", "cc", "bc", "e", "-", "-", "-d", "a-g", "g-e", "f-e", "de", "g-f", "e-ge", "f-d", "gf", "fe", "dd", "gg", "edc", "-g", "cd", "fe", "e", "dc", "bc-a", "-", "-", "-a", "cd", "fe", "e", "dc", "bc-e", "-", "-", "eg", "fa", "ggf", "ee", "eg", "-", "f", "-", "-e", "gf", "fe", "dd", "-d", "c", "-", "-", "", "", "", "-e", "-fe ", "gf", "fe", "ed", "cd", "fe", "ed", "c", "-ee", "fe", "ed", "cc", "b", "cc", "ed", "-e", "-fe ", "gf", "f", "ed", "cd", "fe", "ed", "c", "-ee", "fe", "ed", "cc", "b", "ca", "-", "g", "c", "e", "-", "e", "f", "e", "c", "-", "-gb", "d", "-", "e", "f", "e", "c", "-", "-gd", "c", "-", "e", "f", "e", "c", "-", "-gf", "d", "-", "e", "f", "e", "c", "-", "-bg", "c", "-"],
  "barrishlete": ["b", "cd", "e", "b", "c", "-", "-", "-", "b", "cd", "e", "b", "a", "b", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "cd", "eb", "cd", "eb", "cg", "-", "-", "-g", "gf", "fe", "ed", "cb", "d", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "ab", "d-c", "d-c", "d-c", "d-c", "dde", "dc", "c", "-", "a", "b", "c", "f", "-", "-", "-", "-", "a", "b", "c", "e", "-", "-", "-", "-", "d", "c", "b", "c", "f", "-", "-", "-", "a", "b", "c", "e", "-", "-", "-", "-", "e", "d", "b", "c", "f", "-", "-", "-e", "d", "e", "- db", "c", "-", "-", "cd", "ega", "b", "-d", "b", "c", "-", "-", "-a"],
  "asalmein": ["bc", "ce", "d", "-", "bc", "ce", "d", "-", "gg", "gc", "b", "d", "cbg", "d", "-", "-", "bc", "ge", "d", "-", "bc", "cdf", "ed", "-", "gg", "gc", "b", "gc", "b", "d", "-", "-", "c", "cb", "c", "cb", "e", "d", "ed", "-", "c", "cb", "c", "cb", "ga", "g", "-", "-", "gg", "agf", "e", "-", "gg", "agf", "e", "-", "ggg", "agf", "e", "-", "d", "fe", "cd", "-", "g", "c", "d", "e", "g", "e", "d", "b", "bbb", "ba", "bbb", "ba", "dd", "dg", "g", "-", "bbb", "ba", "bc", "ba", "dd", "dg", "g", "-", "de", "d", "c", "-", "c-c", "bc", "ed", "-", "df", "ee", "cd", "-", "c", "gf", "e", "-", "c", "gf", "ee", "-", "c", "gf", "e", "-", "de", "fe", "d", "-", "c", "gf", "e", "-", "ga", "gf", "e", "ed", "dec", "dd", "d", "-",
    "cc", "ba", "a", "a", "ab", "d", "ba", "a",
    "cb", "ag", "g", "-d", "g", "a#", "a",
    "edc",
    "gg", "e", "gg", "ge", "gg", "ag", "ed", "d", "gg", "e", "gg", "g-c", "bc", "bc", "ag", "g", "cd", "ef", "ed", "cb", "c", "c", "c", "cb", "d", "-", "-", "cd", "c", "b", "ag", "agg"
  ],
  "terebin": ["cb", "cb", "cb", "cb", "cb", "cb", "cb", "cd", "cde", "def", "ed", "cb", "cb", "cb", "cb", "cb", "cb", "cb", "cbc", "ed",
    "c", "b", "g", "-", "-", "-", "-", "-ag", "f", "e", "g", "-", "-", "-", "-", "-", "f", "a", "c", "b", "-", "-", "-", "-", "f", "a", "c", "b", "-", "-", "-", "-", "g", "a", "g", "e", "d", "e", "f", "e", "-", "-", "-", "-", "g", "gg", "gg", "g", "gg", "gg", "e", "f", "g", "cb", "cb", "cd", "f", "ff", "ff", "f", "ff", "ff", "f", "a",
    "b", "cb", "ag", "fe", "b", "c", "g", "f", "e", "-", "-", "-", "-", "-", "-", "-",
    "e", "f", "g", "a#", "a", "-", "-", "-", "c", "e", "f", "a", "g", "-", "-", "-", "e", "f", "g", "a#", "a", "-", "-", "-", "b", "cb", "a", "b", "c", "-", "-", "-"
  ],
  "dekhahajaro": ["c", "d", "edcd", "ec", "de", "fe", "d", "b", "c", "d", "b", "d", "bd", "cba", "aab", "cbab", "cbac", "b", "eee", "db", "bb", "bd", "c", "c", "d", "edcd", "ec", "de", "fe", "d", "b", "c", "d", "b", "d", "bd", "cba", "aab", "cbab", "cbac", "b", "eee", "db", "bb", "bd", "c", "egcb", "dc", "a", "fg", "egcb", "dc", "a", "fa", "g", "g", "f", "ede", "cba", "b", "f", "a", "a", "g", "fef", "gd", "dfe", "gf", "ef", "a", "-", "gf", "ef", "g", "-", "g", "g", "f", "ede", "cba", "b", "f", "-", "a", "a", "g", "fef", "gd", "dfe", "-", "c", "d", "edcd", "ee", "fe", "d", "b", "c", "d", "b", "d", "ed", "e-dc", "aab", "cbab", "cbac", "b", "eee", "db", "bb", "bd", "c"],
  "gogolagu": ["e", "e", "f", "g", "-", "a", "fg", "e", "e", "f", "g", "a", "b", "-", "ga", "g", "g", "g", "b", "b", "c", "-", "de", "cd", "f", "fe", "de", "dc", "c", "-", "gag", "fe", "ee", "dc", "ef", "g", "-", "-", "gag", "fe", "ee", "dc", "ef", "g", "-", "-",
    "-ga", "cc", "bbb", "ag", "gag", "fe", "ef", "g", "-", "-", "-ga", "cc", "bbb", "ag", "gag", "fe", "ef", "g", "-", "-",
    "gag", "f", "ee", "dc", "bc", "d", "-", "-", "gg", "b", "cc", "de", "dc", "c", "-", "-",
    "gg", "b", "cc", "de", "dc", "c", "-", "-",
    "ef", "gg", "gg", "gaag", "gc", "cc", "ba", "g", "bc", "dd", "d", "def", "ge", "ded", "c", "-", "ef", "gg", "gg", "gab", "cb", "abag", "a", "-", "gaa", "aa", "ag", "fg", "gf", "edcd", "e", "-", "bc", "db", "c", "-", "bc", "db", "c", "cd", "ef", "g", "ga", "cd", "e", "dc", "b", "ga", "bb", "c",
    "ga", "cd", "e", "dc", "b", "ga", "bb", "c",
    "bc", "cc", "b", "a", "gag", "fe", "e", "f", "g",
    "gag", "f", "ee", "dc", "bc", "d", "-", "-", "gg", "b", "cc", "de", "dc", "c", "-", "-", "gg", "b", "cc", "de", "dc", "c", "-", "-", "g", "ga", "b", "c", "b", "ba", "g", "a", "g", "f", "e", "f", "g", "d", "-", "e", "c", "d", "f", "-", "g", "-", "-", "-", "ded", "c", "ded", "c", "ded", "c", "bcb", "a", "bcb", "a", "bcb", "a", "b", "bc", "db", "c", "g", "fg", "ef", "d"
  ],
  "bolna": ["ab", "cbag", "dcbc", "ab", "cbag", "bagg",
    "bb", "c", "d", "dd", "dd", "de", "gf#", "ee", "edc",
    "a", "b", "bag", "gg", "gaga", "gg",
    "a", "c", "bag", "gg", "accc",
    "bagab", "cbag",
    "bb", "cd", "dd", "def#e", "ef#", "de", "ee",
    "aaa", "bage", "gabag", "ftg", "ef#", "gg",
    "gggg", "gg", "gg", "f#", "ftgag", "f#ee",
    "aaa", "bage", "eed", "dc", "cdcdc", "ba",
    "a", "b", "bag", "gg", "gaga", "gg",
    "a", "c", "bag", "gg", "gaga", "gg"
  ],
  "kmayalagxa": ["gc", "bc", "dc", "ba", "ga", "fg", "fe", "e", "ggc", "bc", "dc", "ba", "ga", "fg", "fe", "e", "e", "ee", "de", "g", "c", "cb", "ag", "g", "e", "ee", "de", "g", "cc", "cb", "ag", "g"],
  "mithila": ["g", "ag", "g", "ag", "g", "ag", "e", "-",
    "g", "ag", "g", "ag", "g", "ag", "ab", "-",
    "gg", "fff", "ff", "eee", "edbag",
    "ga", "cb", "gc", "c", "cd",
    "e-d", "e", "de", "de", "de", "c",
    "cde", "e", "de", "de", "de", "cbg",
    "cb", "dd", "df", "ed", "cb", "ab", "ag", "g",
    "ga", "cb", "ab", "ag", "g", "a", "ggg",
    "ga", "cc", "cb", "ab", "ag", "g",
    "fede", "fg", "agfg", "acb", "cbab", "ced",
    "efe", "gfe", "ded", "cdc", "bc", "ba", "fg",
    "efe", "gfe", "ded", "cdc", "bc",
    "ded", "fed", "cdc", "bcb", "ab",
    "cdc", "edc", "bcb", "aba", "dc", "bc", "d", "g"
  ],
  "marijau": ["e", "d", "-", "e", "g", "-", "d", "e",
    "-", "e", "c", "-", "e", "f", "-", "f", "e", "-", "f", "-", "c", "f", "e", "-",
    "e", "d", "-", "e", "g", "-", "d", "e",
    "-", "e", "c", "-", "e", "f", "-", "f",
    "e", "-", "e", "f", "f", "d", "-", "-",
    "e", "d", "-d", "e", "g", "-", "d", "e",
    "-", "e", "c", "-", "e", "f", "-", "f",
    "d", "-", "e", "f", "f", "e", "-", "-",
    "e", "d", "-", "e", "g", "-", "d", "e",
    "-", "e", "c", "-", "e", "f", "-", "f",
    "e", "-", "f", "-", "c", "f", "e", "-"
  ],
  "piyabole": ["cb", "d", "-", "-", "de", "d", "-", "-",
    "cb", "d", "-", "-", "fd", "e", "-", "-",
    "cb", "d", "-", "-", "ef", "e", "-", "-",
    "cb", "d", "-", "-", "bd", "c", "-", "-",
    "cb", "cd", "-", "ed", "fe", "-", "-", "cb",
    "cd", "-", "-", "cb", "c", "-", "-", "-",
    "c", "gf", "d", "ge", "c", "gf", "d", "ge",
    "c", "gf", "de", "fe", "-", "-", "-", "-",
    "c", "-g", "a", "g", "c", "-g", "a", "g",
    "ga", "g", "ef", "ag", "-", "-", "-", "-",
    "g", "-e", "d", "d", "g", "-e", "d", "d",
    "bd", "b", "c", "fe", "-", "-", "-", "-"
  ],
  "pinkpanther": ["a", "-b", "c", "-a", "ab", "cf", "ea", "cf",
    "d#", "-", "-", "dcbg", "a", "-", "-", "-",
    "a", "-", "c", "-", "a", "-", "f", "-",
    "d#", "-", "-", "-"
  ],
  "smokeonwater": ["a", "c", "d", "-a", "-c", "-e", "d", "-", "a", "c", "d", "-c", "-a", "-", "-", "-"],
  "makurijalai": ["ee", "gg", "ga", "ge", "g", "a", "c", "-", "ga", "ge", "g", "a", "c", "-", "gca", "ca", "ge", "c", "de", "g", "e", "d", "c", "-"],
  "fireflies": ["cg", "gf", "gf", "c",
    "cd", "dc", "df", "g",
    "a-g", "fcc", "cg", "fd",
    "cg", "gf", "gf", "c",
    "cd", "dc", "df", "g",
    "c", "c", "a", "g",
    "f", "c", "c", "a", "g", "d", "f"
  ],
  "titanic": ["f", "f", "f", "f", "e", "f", "f", "e", "f", "g", "a", "g", "f", "f", "f", "f", "e", "f", "f", "c"],
  "rooptera": ["d", "dc", "d", "-", "cd", "dc", "a", "-",
    "d", "dc", "d", "-ed", "cd", "d", "c", "a-", "-",
    "d", "dc", "d", "dc", "d", "dc", "cg", "a-",
    "-", "f", "e", "-", "-", "ded", "cd",
    "a", "c-a", "a", "c", "dc", "ab", "bg", "-",
    "a", "c", "ac", "c", "-ed", "de", "cd", "d",
    "f", "fe", "f", "fe", "f", "fe", "edc", "d",
    "cd", "cd", "cd", "-"
  ],
  "gurjupaltan": ["ga", "f", "ga", "f", "ga", "f", "d", "c", "ga", "f", "ga", "f", "g", "c", "c", "c", "ga", "f", "ga", "f", "ga", "f", "d", "c", "cd", "dc", "c", "c", "c", "-", "-", "-", "cd", "df", "f", "f", "cd", "dc", "c", "c", "c", "-", "-", "-", "-", "-", "-", "-", "f", "-g", "a", "a", "g", "ag", "f", "f", "f", "-g", "a", "a", "g",
    "ag", "-f", "c", "a", "ag", "f", "f", "f", "-", "-", "-",
    "a-c", "dd", "cd", "ff", "gg", "fd", "d-c", "c", "a-c", "dd", "cd", "ff", "gg", "fd", "f", "f", "c", "a", "c", "-a", "cc", "a", "c", "-"
  ],
  "nancy": ["c", "ba", "b", "ag", "ag", "ed", "e", "ef", "g", "fe", "e", "dc", "dc", "ag", "a", "-", "c", "ba", "b", "ag", "ag", "ed", "e", "ef", "ga", "fed", "de", "dc", "dc", "ag", "a", "-", "e", "ee", "ed", "cd", "e", "g", "a", "-", "g", "gg", "ag", "ed", "e", "d", "-", "ed", "c", "cc", "ca", "ga", "e", "g", "a", "-", "g", "gg", "ag", "ed", "c", "-", "-", "-", "cc", "dd", "eg", "a-ag", "gg", "aged", "ee", "e-cd",
    "ee", "dc", "--", "--", "ee", "dcag", "aa", "-", "cd", "ee", "gg", "aa", "gcd", "ee", "dc", "ag", "aa", "ee", "ec", "ag", "g", "dd", "de", "fe", "e", "eee", "dc", "aa", "g", "eee", "d", "g", "aa"
  ],
  "sannani": ["c-cc", "cc", "cc", "g-gb", "ag", "fe", "dc", "-", "c-ef", "g", "cf", "g", "", "ef", "g-gb", "ag", "-", "c-cc", "c-c", "cc", "g-gb", "a-g", "f-e", "d", "c", "gg", "bc", "e", "e", "ed", "cd", "f", "f", "aa", "a", "a", "a#", "ag", "ff", "f", "e", "c-cc", "c", "c", "cded", "cb", "ca", "aa", "a", "a", "a", "a#ag", "agf", "ff", "f", "ga", "d", "de", "dc", "ag", "g", "cc", "c", "b", "d", "-e", "dc", "ab", "f", "ff", "f", "gbag", "fd", "de", "dc", "ag", "d", "gg", "e", "d", "c", "-", "-", "-"],
  "doraemon": ["cba", "gab", "cba", "gab", "cba", "gab", "cba", "g", "dcb", "abc", "dcb", "abc", "dcb", "abc", "fcc", "d", "abc", "fga", "gab", "efg", "fga", "def", "efg", "cde", "dc#", "cb", "a#a", "g#g", "f#f", "ed#", "d", "-"],
  "tungnakodhun": ["e", "ec", "dc", "c", "ee", "ec", "dc", "c", "aa", "ac", "ag", "g", "ga", "ca", "c", "d", "g", "-", "-", "-", "cd", "ed", "ca", "cd", "ga", "ab", "ag", "e", "e", "eg", "ed", "dc", "cd", "dg", "g", "-"],
  "korakagaz": ["ga", "cd", "ded", "-c", "", "ag", "ad", "-", "-", "ga", "cd", "ed", "-c", "ba", "bc", "-", "-", "ed", "ed", "c", "ag", "ga", "cd", "ec", "d", "ed", "ed", "cb", "ag", "ga", "cc", "d", "c", "ee", "ef", "ef", "ed", "dd", "de", "de", "c", "cc", "d", "-", "c", "a", "-", "-", "-"],
  "irishwasherman": ["gf", "ecc", "gcc", "ece", "gfe", "bdd", "add", "fdf", "agf", "ecc", "gcc", "ece", "gfe", "fef", "dgf", "dcc", "c-g", "cgc", "cgc", "cgc", "edc", "bgb", "bgb", "bgb", "dcb", "acc", "gcc", "fcc", "ecc", "fef", "dgf", "ecc", "c"],
  "gulabi": ["ee", "e", "c", "c", "cb", "c", "d", "b", "ba", "b", "c", "a", "a", "g", "a", "b", "e", "f", "ae", "-", "e", "f", "af", "-", "f", "g", "a", "ba", "ab", "ag", "af", "e", "b", "c", "d", "e", "-", "-", "fe", "fe", "dc", "b", "cd", "-", "ed", "ed", "cb", "a", "bc", "-", "dc", "dc", "ba", "g", "ab", "-"],
  "fairytail": ["aba", "ge", "deg", "ag", "aba", "ge", "deg", "cb", "aba", "ge", "deg", "ag", "cba", "bag", "egag", "cb", "abc", "bd", "ce", "dcb", "abc", "bd", "ce", "dcb",
    "a-", "e-", "--", "-da", "c-", "b-", "a-", "b-", "a-", "e-", "g-", "-ef", "dg", "cb", "a-", "g-",
    "a", "ab", "c", "ba", "g", "e", "-", "dc", "d", "-c", "d", "cb", "a", "-", "b", "-", "a", "ab", "c", "ba", "ge", "ge", "-", "dc", "d", "-e", "d", "cb", "a", "bc", "b", "g"
  ],
  "ntc": ["ae", "de", "cd", "cb", "ae", "de", "cdeg", "d", "gg", "ge", "ag", "ed", "dedc", "dcb", "dc", "ba", "ae", "de", "cde", "edcb", "bcde", "dcbc", "a", "-"],
  "closer": ["cd", "ee", "fd", "cd", "bcd", "efe", "dd", "dc", "cef", "f", "ece", "cd", "cef", "gd", "cbc", "c"],
  "alankar": ["-e", "de", "cd", "e-", "-e", "de", "cd", "f-", "-e", "de", "cd", "g-", "fe", "fe", "dc",
    "-", "-f", "ef", "de", "f-", "-f", "ef", "de", "g-", "-f", "ef", "de", "a-", "gf", "gf", "ed", "-",
    "-g", "fg", "ef", "g-", "-g", "fg", "ef", "a-", "-g", "fg", "ef", "b-", "ag", "ag", "fe", "-",
    "-a", "ga", "fg", "a-", "-a", "ga", "fg", "b-", "-a", "ga", "fg", "c-", "ba", "ba", "gf", "-",
    "-b", "ab", "ga", "b-", "-b", "ab", "ga", "c-", "-b", "ab", "ga", "d-", "cb", "cb", "ag", "-",
    "-c", "bc", "ab", "c-", "-c", "bc", "ab", "r-", "-c", "bc", "ab", "e-", "dc", "dc", "ba", "-",
    "cb", "ab", "ag", "-b", "-a", "ga", "gf", "-a", "-g", "fg", "fe", "-g", "-f", "ef", "ed", "c-"
  ],
  "ektarfa": ["bb", "bb", "bcc", "ba", "g", "-", "-", "-",
    "bb", "bb", "bcc", "ba", "g", "-", "-", "-",
    "bb", "bb", "bcc", "ba", "g", "-", "-", "-",
    "bb", "bb", "dc", "ba", "g", "-", "-", "-",
    "cc", "dddf", "ffg", "f", "ee", "dc", "d", "-",
    "cc", "gf", "ffff", "gf", "ee", "", "edc", "c", "-",
    "gg", "dd", "cc", "cc", "cc", "de", "dc", "ba",
    "aa-a", "aa-a", "ag", "gaa", "ab", "bcc", "", "ba", "gg",
    "ed", "ed", "ed", "egfg", "e", "dc", "dcb", "a",
    "g", "gb", "a", "-", "gf", "g", "-", "-",
    "gg", "gc", "aa", "-", "gf", "g", "-", "-",
    "g", "gb", "a", "-", "gf", "g", "-", "-",
    "gg", "cb", "g", "-",
    "gg", "gc", "aa", "-", "gf", "g", "-", "-"

  ],
  "lyamadaju": ["cd", "ef", "f", "f", "g", "ga", "f", "-", "e", "d", "df", "ed", "c", "c", "b", "-", "-", "g", "b", "-", "c", "-", "d", "de", "cd", "g", "f", "e", "d", "e", "d", "cd", "b", "c", "-", "--", "g", "g", "g", "ga", "ab", "b", "-", "-", "bc", "-c", "d", "c", "c", "b", "-", "a", "a", "g", "g", "ga", "ab", "b", "-", "-", "bc", "-c", "d", "c", "c", "b", "-", "a", "a", "g", "g", "f", "f", "e", "d", "", "f", "e", "d", "c", "c", "b", "-", "-", "g", "b", "b", "c", "-", "d", "de", "cd", "g", "f", "e", "d", "e", "d", "c", "b", "c", "-", "-"],
  "hayejyapunitata": ["-", "g", "-g", "c", "cc", "a#", "a", "g", "d", "f", "ga", "g", "fe", "ef", "d", "c", "-", "b", "-b", "b", "c", "c", "df", "f", "-", "df", "ga", "g", "fe", "ef", "d", "c", "-", "cd", "-d", "d", "d#", "-", "d", "c"],
  "manakihum": ["de", "-d", "e", "dc", "de", "-d", "e", "-", "de", "-d", "e", "ag", "e", "d", "-", "-", "c", "b", "a", "b", "c", "e", "-", "-", "d", "f", "e", "-", "e", "ed", "g", "f", "f", "e", "d", "-", "e", "f", "a", "e", "de", "-", "-", "dc", "cd", "cba", "fa", "ag", "g", "df", "fe", "-", "c", "b", "a", "b", "c", "g", "-a", "fe", "ga", "gaa", "ga", "gaa", "bb", "c", "ba", "ag", "g", "c", "ag", "f", "g", "c", "ag", "dcag", "cb", "ga", "g", "-", "gaa", "gaa", "gcc", "a", "b", "dc", "b", "ba", "ag", "ag", "gg", "-"],
  "dancemonkey": ["ag", "ag", "ag", "ag", "ac", "b", "-", "-", "cc", "ba", "ag", "ag", "ac", "b", "-", "-", "-g", "ag", "ag", "ag", "ag", "ac", "b", "-"],
  "spongebob": ["ge", "ce", "ec", "eg", "bag", "dca", "ca", "ge", "dc", "df", "ef", "fed", "gf", "gb", "c", "g"],
  "wisemansay": ["c", "-", "-", "-", "g", "-", "-", "-", "c", "-", "-", "-", "d", "e", "f", "-", "e", "-", "-", "-", "d", "-", "-", "-", "g", "d", "-", "-", "n", "-", "-", "-", "c", "-", "-", "-", "d", "e", "f", "-", "e", "-", "-", "-", "d", "-", "-", "-", "c", "-", "-", "-"],
  "krishna": ["c", "cd", "e", "f", "ef", "gf", "e", "d", "cd", "cb", "cc", "dd", "fe", "dc", "c", "c",
    "g", "gcc", "c", "ba", "ba", "gf", "fg", "g", "g", "gba", "fe", "dc", "e", "d", "-", "-", "bc", "-", "-", "fe", "bc", "-", "-", "-"
  ],
  "krishnalila": ["cd", "cd", "eg", "eg", "a", "-", "-", "-", "b", "cb", "g", "-", "e", "-", "-", "-", "cd", "e", "c", "g", "-", "c", "ed", "-", "cb", "a", "cb", "c", "-", "-", "-", "-", "cb", "a", "-b", "g", "e", "-", "-", "-", "de", "f", "-", "-", "de", "f", "-", "-", "de", "f", "a", "cb", "b", "-", "ge", "d", "-", "-", "-", "-", "-", "-", "-", "-", "cb", "cb", "cd", "cd", "e", "-", "-", "-", "ed", "ed", "ed", "eg", "b", "-", "-", "-", "cb", "a", "-b", "ge", "-", "-", "-", "-", "f", "e", "d", "ef", "d", "ef", "d", "-"],
  "wokishnahai": ["c", "g", "-", "", "fe", "d", "f", "-", "ed", "c", "e", "-", "dc", "d", "-", "-", "-", "c", "g", "-", "", "fe", "d", "f", "-", "ed", "c", "e", "-", "dc", "c", "-c", "ab", "c", "-c", "ab", "d", "ed", "-c", "ab", "c", "-"],
  "untamed_G": ["e", "-", "c", "a", "b", "g", "e", "-", "a", "bc", "d", "g", "a", "-", "-", "-", "e", "-", "c", "a", "b", "g", "e", "fg", "a", "-", "dc", "bc", "b", "-", "-", "-", "cd", "e", "d", "cb", "ca", "b", "a", "g", "cd", "ef", "g", "d", "e", "-", "-", "-",
    "d", "eg", "c", "-", "bc", "e", "a", "-", "g", "g", "e", "c", "cd", "ed", "eg", "a", "-", "-", "-", "-", "eg", "a", "c", "b", "a", "g", "e", "-dg", "e", "ab", "c", "ab", "ag", "e", "-", "-", "fg", "a", "c", "b", "a", "g", "e", "eb", "a", "ag", "ac", "b", "g", "a", "-", "-",
    "c", "-", "-", "dg", "e", "-", "-", "-", "c", "-", "-", "da", "g", "-", "-", "g", "c", "-", "-", "dg", "e", "-", "e", "ca", "d", "-", "-", "-", "-", "-", "cd", "ag", "c", "-", "-", "-"
  ],
  "asarai": ["a", "-", "-", "-", "-", "-", "c", "e", "d", "-", "-", "-", "-", "-", "b", "g", "a", "-", "-", "-", "-", "-", "-", "-", "-e", "-", "G", "-", "Ab", "AE", "D", "-", "-", "-", "b", "AG", "G", "Ab", "A", "-", "-", "-", "-", "-", "Ab", "AE", "D", "-", "-", "-", "b", "b", "C", "-", "-", "-", "ED", "Cb", "Ab", "G", "-e", "A", "-", "bC", "b", "AG", "e", "-_#", "e", "A", "-", "bD", "b", "AG", "G", "-", "-e", "e", "b", "-A", "e", "ed", "e", "-", "c", "ca", "e", "dc", "c", "-", "-", "-", "e", "A", "-", "bC", "b", "-", "AG", "Ab", "A", "-", "-", "-", "-", "-", "-", "-", "E", "-", "D", "-", "bG", "Ab", "A", "-", "-G", "E", "-", "E", "D", "D", "C", "A", "A", "AD", "D", "DC", "C", "-", "A", "G", "G", "E", "-", "E", "D", "C", "A", "A", "AD", "D", "DC", "C", "-", "-", "-", "-GA", "A", "-", "C", "A", "AG", "e", "-", "eG", "G", "-", "Ab", "G", "de", "d", "-", "cd", "d", "-", "eG", "e", "dc", "c", "-", "e", "A", "-", "bC", "b", "-", "AG", "Ab", "A", "-", "-", "-", "-", "-", "-", "-", "E", "-", "D", "-", "bG", "Ab", "A", "-"],
  "oncscale": ["c", "d", "e", "f", "g", "a", "b", "c", "c#", "d#", "f#", "g", "g#", "a#", "c", "c#",
    "d", "e", "f#", "g", "a", "b", "c#", "c",
    "d#", "f", "g", "g#", "a#", "c", "d", "d#",
    "e", "f#", "g#", "a", "b", "c#", "d#", "e"
  ],
  "jhanjaka": ["c", "cc", "e", "f", "a", "-", "ab", "Cb", "g", "-", "e", "f", "e", "c", "-", "b", "a", "b", "g", "a", "d", "-", "cb", "ab", "c", "-", "-", "-", "-", "c", "e", "f", "a", "a", "a", "-", "-", "ab", "-C", "b", "g", "g", "f", "e"],
  "rajamati": ["gg", "ga", "CC", "C", "-CD", "ED", "CCB", "AG", "-", "GA", "-B", "B", "B", "AG", "-A", "B", "G", "-", "-", "C", "BC", "AB", "GA", "G", "-", "ga", "aa", "ab", "ag", "ga", "gf", "ee", "dc", "cd", "ee"],
  "chamcham": ["-", "e", "c", "-", "b", "c", "-", "bg",
    "-", "c", "c", "-d", "e", "ec", "-", "-",
    "e", "c", "c-c", "b", "c", "-", "bg", "-",
    "-", "c", "c", "-d", "e", "ec", "-", "-",
    "cc", "d", "e", "dc", "-", "c", "-", "d",
    "-", "-", "-", "-", "-", "-", "-", "-",
    "-", "-", "-", "-", "-", "-", "-", "-",
    "e", "dc", "dc", "c", "e", "dc", "dc", "c",
    "e", "dc", "cc", "ga", "-", "-", "-", "-",

    "c", "c", "g", "cd", "e", "-", "c", "-",
    "c", "c", "g", "cd", "e", "d", "c", "-",
    "e", "e", "g", "ed", "dc", "ddc", "de", "d"
  ],
  "parelima": ["-", "e", "e", "p", "f", "-", "-", "-",
    "-", "f", "f", "p", "p", "-", "ed", "c",
    "-", "p", "e", "d", "c", "-", "a", "p",
    "-", "a", "a", "b", "a", "-", "ed", "c",
    "-", "c", "c", "c", "f", "-", "f", "-",
    "a", "g",
    "-", "a", "a", "a",
    "-", "a", "a", "e", "a", "b", "c", "d",
    "b", "-", "a", "p", "-", "-", "-", "-",
    "-", "a", "a", "e", "a", "b", "c", "d",
    "b", "-", "-", "-", "-", "-", "-", "-",
    "-", "f", "f", "f", "f", "a", "a", "c",
    "c ", "-g", "f", "e",
    "c", "d", "g", "e", "c", "-g ", "f", "e",
    "c", "d", "c", "c"
  ],
  "bhijyotmro": ["gg", "g", "gc", "b", "ag", "a", "gf", "g",
    "-", "fd", "c", "-",
    "-", "f", "ga", "-",
    "aa", "a", "a", "a", "b", "a", "g", "f",
    "ffe", "de", "cd", "ffe", "de", "d", "c", "c",
    "-", "-", "-", "e", "f", "g", "a", "-",
    "c", "-d", "f", "ga", "g", "-f", "d", "-",
    "-g", "gf", "-g", "gf", "d", "dc", "bc", "c",
    "c", "-", "-", "-", "-", "-", "-", "-"
  ],
  "prempatra": ["-", "g", "g", "-ga", "b", "d", "-", "-",
    "c", "c", "d", "b", "a", "-", "b ", "-",
    "-", "g ", "g", "-g", "b ", "d", "-", "-",
    "c", "c", "d", "b", "a", "-", "b ", "-",
    "-g", "a", "-", "g", "-", "d", "a", "-",
    "b", "-", "b", "c", "-", "b", "c", "-",
    "-", "b", "ab", "-", "a", "-", "b", "d",
    "d", "b-g", "a", "-", "g", "-", "b", "d",
    "d", "b-g", "b", "-", "a", "-", "edc", "e",
    "d", "b-g", "a", "-", "g", "-"
  ],
  "tmletahoina": ["g", "ge", "-", "eg", "f", "ed", "-", "dd",
    "e", "d", "c", "b", "a", "-", "-", "-",
    "a", "b", "c", "e", "d", "dd", "-", "bd",
    "d", "c", "-", "-", "-", "-", "-", "-",
    "g", "c", "b", "c", "ce", "ed", "b", "c",
    "c ", "e ", "d", "f", "e", "-", "-", "-",
    "e ", "f", "g", "b", "a", "ag", "f", "g",
    "a", "g", "-", "-",
    "e", "f", "g", "a", "-a", "b", "ba", "gf",
    "-f", "g", "-f", "g", "e", "ed", "c", "-",
    "c", "cg", "fा", "g", "e", "ed", "bd", "dc",
    "bbb", "c", "-", "-", "e", "c", "-", "-",
    "bbb", "c", "-", "-", "e", "-", "-", "-",
    "ge", "fg", "-", "-", "bag", "fg", "-", "-",
    "bbb", "c", "-", "-", "e", "-", "-", "-",
    "", "e", "f",
    "g", "-", "-", "-", "b", "a", "f", "g",
    "e", "-", "-", "-", "-", "b", "a", "b",
    "a", "-", "-", "-", "a", "b", "c", "f",
    "e", "-", "-", "-", "-", "-"
  ],
  "bajhokhet": ["e", "g", "a", "c", "a", "g", "e", "d",
    "d", "e", "g", "a", "g", "e", "d", "c",
    "c", "d", "e", "g", "e", "d", "c", "a",
    "ac", "ac", "c", "-", "dc", "dc", "c", "-",
    "c", "c", "c", "c", "d", "c", "a", "-",
    "g", "a", "c", "-", "d", "e", "-", "-",
    "cc", "dc", "-c", "dc", "cc", "dc", "-c", "dc",
    "d", "e", "g", "-", "d", "g", "e", "d",
    "c", "c", "-", "d", "e", "c", "d", "-",
    "a", "c", "c", "-", "c", "-", "-", "-",
    "c", "d", "c", "e", "c", "d", "c", "e",
    "-", "eg", "-g", "g", "f", "-", "e", "d",
    "-", "df", "f", "ed", "e", "-d", "c", "b",
    "-", "bc", "d", "e", "d", "-c", "c", "-",
    "-", "eg", "g", "g", "a", "-a", "-", "g",
    "e", "g", "a", "g", "d", "e", "-", "-",
    "gg", "dc", "-c", "dc", "gg", "dc", "-c", "dc",
    "-", "dd", "d", "d", "d", "-e", "-", "g",
    "d", "e", "d", "c", "a", "c", "-", "-",
    "d", "e", "g", "-", "d", "g", "e", "d",
    "c", "c", "-", "d", "e", "c", "d", "-",
    "a", "c", "c", "-", "c", "-", "-", "-"
  ],
  "hekancha": ["d", "-c", "dc", "b", "-", "-", "-", "-",
    "c", "-b", "cb", "a", "-", "-", "-", "-",
    "d", "-c", "dc", "b", "c", "-b", "cb", "a",
    "d", "c", "b", "c", "c", "b", "a", "g",
    "d", "g", "b", "bd", "c", "ba", "g ", "fe",
    "d", "e", "c", "d", "c", "b", "-", "-",
    "d", "d", "a", "-", "b", "cb", "a", "b",
    "e", "ef", "d", "e", "g", "g", "-", "-",
    "d", "d", "cb", "ab", "d", "d", "cb", "ab",
    "d", "d", "cb", "ab", "d", "d", "-", "-",
    "d", "d", "cb", "ab", "d", "d", "cb", "ab",
    "d", "d", "cb", "ab", "b", "b", "-", "-",
    "d", "e", "g", "-", "c", "d", "e", "-",
    "d", "d", "cb", "ab", "d", "d", "-", "-",
    "b", "b", "a", "-", "e", "e", "a", "-",
    "e", "ef", "d", "e", "g", "g", "-", "-",
    "d", "eg", "ag", "ed", "e", "ga", "ba", "ge",
    "g", "ab", "ed", "ba", "g", "-", "-", "-",
    "fg", "-f", "ef", "-e", "de", "-d", "ba", "g",
    "de", "fg", "ab", "cd"
  ],
  "moomin": ["gg", "-g", "a", "g", "gg", "-g", "a", "g",
    "gg", "e", "-", "-", "c", "-", "-", "-",
    "gg", "-g", "a", "g", "gg", "-g", "a", "g",
    "gg", "f", "-", "-", "d", "-", "-", "-",
    "gg", "g", "a", "a", "aa", "a", "b", "a",
    "cc", "c", "dcd", "dcd", "dc", "cc", "a", "g",
    "bb", "d", "-", "c", "-", "-", "-", "-",
    "ggg", "aaa", "bbb", "c", "cgc", "dcd", "ec", "d", "c", "c", "a", "g", "e", "g", "a", "g"
  ],
  "kahilekahi": [
    "a", "ed", "cdcb", "abag", "-", "-", "-", "-", "-",
    "-", "-", "-", "-", "-", "-", "-",
    "aac", "bag", "g", "-", "ba", "aac", "bag", "g",
    "aab", "aa", "aab", "aa", "aac", "ba", "a", "-",
    "-", "-", "-", "-", "-", "-", "-", "-",
    "ed", "dd", "fd", "ed", "ed", "dd", "fd", "ed",
    "ed", "dd", "fd", "ed", "b", "c", "d", "-",
    "-", "-", "-", "-", "-", "-", "-", "-",
    "cc", "cc", "ce", "d", "cce", "dd", "d", "-",
    "ad", "d", "ed", "d", "ad", "d", "bc", "b",
    "df", "eddc", "ce", "dcba", "bd", "cbag", "bc", "d",
    "ad", "d", "ed", "d", "ad", "d", "ab", "g",
    "df", "eddc", "ce", "dcba", "bd", "cbag", "ab", "g"
  ],
  "sawanikhola": ["e", "ee", "df", "g", "ga", "-ba", "g", "gdf",
    "dfg", "dfg", "e", "-", "e", "eg", "df", "ed",
    "c", "b", "a", "-b", "c", "-", "ded", "cd",
    "de", "-", "-", "-", "e", "eg", "df", "ed",
    "c", "b", "a", "-b", "c", "-e", "ded", "cd",
    "c", "-", "-", "-",
    "ac", "ac", "-", "-", "-", "-e", "d", "c",
    "a", "-", "a", "-", "ea", "ea", "-", "-",
    "-", "-d", "c", "a", "g", "-", "g", "-",
    "e", "ee", "df", "dfdf", "g", "gg", "ag", "dfe",
    "e", "ee", "df", "g", "df", "-g", "ed", "c",
    "e", "ee", "df", "g", "dfg", "dfg", "e", "-",
    "ga", "ba", "g", "df", "df", "dfe", "d", "d",
    "a", "a", "b", "c", "d", "c", "c", "-",
    "-", "-", "-", "-"
  ],
  "sayathari": [
    "ggg", "ac", "-", "dc",
    "cc", "dd", "ee", "dc", "ed", "ed", "ed", "ed",
    "dd", "ee", "gg", "ed", "dc", "dc", "dc", "dc",
    "-ed", "ed", "c", "g", "ag", "ed", "e", "-",
    "-ed", "ed", "c", "g", "ag", "ed", "d", "-",
    "-", "dfa", "aba", "ggf", "g", "-gf", "g", "g",
    "gf", "fe", "ed", "dc", "cda", "-ca", "g", "acde",
    "-ed", "ed", "c", "g", "ag", "ed", "e", "-",
    "c", "c", "-", "ba", "-", "gaca", "e ", "dc",
    "cd", "a", "-", "ag", "-", "gagf", "g", "-",
    "-bc", "dg", "f", "ed", "-f", "ed", "c", "b",
    "-bc", "df", "dfg", "ag", "-fe", "db", "c", "-",
    "ee", "ff", "ee", "dd", "ee", "ff", "ee", "e",
    "-eg", "cb", "bdb", "ag", "ag", "fg", "a", "-",
    "-gb", "dc", "ba", "d", "ba", "gae", "g", "-",
    "g ", "ed", "e", "dc", "dc", "ae", "d", "-",
    "g ", "ed", "e", "dc", "dc", "ad", "c", "-",
    "c", "de", "g", "ed", "ce", "dc", "a", "-",
    "c", "de", "g", "ed", "ce", "da", "c", "-",
    "-eg", "cb", "bdb", "ag", "ag", "fg", "a", "-",
    "-gb", "dc", "ba", "d", "ba", "gae", "g", "-",
    "-e", "ga#", "a#a#", "a#a#", "ag", "fe", "d", "-",
    "-df", "gf", "ed", "g", "ed", "cda", "c",
    "gg", "aa", "cc", "dd", "aa", "ff", "ged", "c",
    "c", "a", "-", "-", "ca", "ca", "ca", "ca",
    "c", "g", "-", "-", "ag", "ag", "ag", "ag",
    "c", "a", "-", "-", "ca", "ca", "ca", "gace",
    "e", "-", "-", "-", "e", "-", "-", "-",
    "g", "-f", "ag", "-e", "-", "-d", "c", "-",
    "-a", "c", "e", "e", "e", "-", "-", "-",
    "-gf", "ag", "e", "dc", "-ac", "ee", "e", "e",
    "fga", "e", "efg", "d", "def", "edc", "c", "-",
    "fga", "e", "efg", "d", "fga", "efg", "def", "edc",
    "c", "-", "-", "-"
  ],
  "ohmaicha": ["de", "g", "gag", "fe", "-efe", "ce", "d", "-",
    "cd", "de", "ee", "ef", "gf", "ed", "d", "-",
    "-", "-", "-", "-", "-", "-", "-", "-",
    "d", "de", "gg", "ga", "ba", "gf", "e", "-",
    "ee", "ee", "ef", "gf", "ed", "df", "fedb", "-",
    "-", "-", "-", "-", "-", "-", "-", "-",
    "d", "df", "f", "f", "d", "df", "f", "f",
    "d", "f", "g", "c", "a", "-", "-", "-",
    "e", "ea", "a", "a", "e", "ea", "a", "a",
    "c", "b", "a", "g", "g", "-", "-", "-",
    "ba", "ga", "ba", "ga", "ba", "gf", "ee", "-",
    "ee", "ec", "ee", "ef", "gf", "ed", "dd", "-",
    "d", "df", "f", "f", "d", "df", "f", "f",
    "d", "f", "g", "c", "e", "-", "-", "-",
    "e", "ea", "a", "a", "e", "ea", "a", "a",
    "c", "b", "a", "g", "g", "-", "-", "-",
    "d-d", "d-d", "d-d", "de", "gf", "ed", "e", "-",
    "c-c", "c-c", "c-c", "de", "ac", "ba", "g", "-"

  ],
  "lukkichupi_Gs": ["ed", "dc", "-c", "d", "da", "-", "-", "-",
    "ga-c", "c", "-", "-", "cd", "c", "e", "-",
    "-", "-", "eg", "eg", "-ga", "g", "ed", "eadde", "e", "ffe", "-d", "c", "aa", "-", "ac", "dc", "d",
    "-", "-",
    "-", "e", "e", "ed", "eg", "e", "-d", "ca",
    "c", "-d", "d", "", "dc", "de", "d", "dc", "a", "ag", "ga", "c", "-e", "dc", "cd", "fe", "-", "g",
    "g", "g", "g", "ga", "ag", "fe", "f", "ga", "-ga", "g", "ed", "c", "a", "-", "-"
  ],
  "ratorani": ["ad", "dd", "eg", "ed", "ded", "ca", "", "-", "-dd", "f-ed", "d", "-", "eg", "ed", "dd", "ca", "ad", "ddc", "edc", "c", "a", "g-a", "c", "e-g", "ed", "d-d", "ad", "-", "-", "g-a", "cd", "e-g", "ed", "d-d", "ad", "-", "-",
    "de", "d-ca", "de", "d-ca", "c", "-", "-", "-",
    "ed", "cde", "g-g", "-a", "g", "ed", "-", "-",
    "dc", "d", "g-g", "-g", "e", "dc", "-", "-",
    "g", "ga", "ge", "dc", "d", "de", "dc", "aagg", "gg", "e-g", "e-r", "dd", "ca", "d", "-",
    "cd", "e-e", "de", "ca", "ddf", "ec", "c", "-"
  ]
};
let songkolagijson = {};

function arrayToJson() {
  songList.forEach(slist => {
    songkolagijson[slist] = note[slist].join();
  });
}

function loadDoc() {
  var xhttp = new XMLHttpRequest();
  xhttp.onreadystatechange = function () {
    if (this.readyState == 4 && this.status == 200) {
      document.getElementById("demo").innerHTML =
        this.responseText;
    }
  };
  xhttp.open("GET", "ajax_info.txt", true);
  xhttp.send();
}
/*

  "rajamati": ["-", "gg", "-g", "a", "C", "C", "C", "-", "-", "CD", "-E", "D", "C", "CB", "A", "G", "-", "GA", "-B", "B", "B", "AG", "-A", "B", "G", "-", "-", "C", "BC", "AB", "GA", "G", "-", "ga", "aa", "ab", "ag", "ga", "gf", "ee", "dc", "cd", "ee"]
 */


var songList = [
  "temp",
  "alankar",
  "spongebob",
  "untamed_G",
  "wisemansay",
  "wokishnahai",
  "jhanjaka",
  "tmletahoina",
  "oncscale",
  "krishna",
  "krishnalila",
  "terebin",
  "kahilekahi",
  "sawanikhola",
  "sayathari",
  "moomin",
  "lukkichupi_Gs",
  "ohmaicha",
  "prempatra",
  "hekancha",
  "ratorani",
  "chamcham",
  "bhijyotmro",
  "asarai",
  "bajhokhet",
  "rajamati",
  "ektarfa",
  "dancemonkey",
  "hpd",
  "ntc",
  "gulabi",
  "dekhahajaro",
  "lyamadaju",
  "hayejyapunitata",
  "rooptera",
  "bolna",
  "janenahi",
  "korakagaz",
  "manakihum",
  "jasnebahara",
  "piyabole",
  "fairytail",
  "barrishlete",
  "asalmein",
  "closer",
  "afreen",
  "smokeonwater",
  "titanic",
  "pinkpanther",
  "sannani",
  "makurijalai",
  "fireflies",
  "nancy",
  "mithila",
  "marijau",
  "irishwasherman",
  "kmayalagxa",
  "gogolagu",
  // "doraemon",
  "gingle",
  "sakura",
  "jasmineflower",
  "riverflowsintoyou",
  "tungnakodhun",
  "farewelltoireland",
  "binksake",
  "simauta",
  "prayas",
  "gurjupaltan",
  "ntc",
  "lilbrownjug",
  "twinkle",
  "ogreenland",
  "flowerofedinburgh",
  "wochugalli",
  "jigubaisha",
  "tknt"
]

songs = document.querySelector("#songs");
songstwo = document.querySelector("#songstwo");
songList.forEach((song, index) => {
  option = document.createElement("option");
  option.value = ("note." + song);
  option.innerHTML = song;
  songs.append(option)

  li = document.createElement("li");
  li.id = ("note." + song);
  li.innerHTML = (index + 1) + ". " + song;
  songstwo.append(li)

})




// ef ed "gg"
//  "gg" a fe def
// "gg" gaga fg
// "gg" ga fg ed
// "gg" g bca  agf gfd


console.log(note.hpd[0]);
var mydata = JSON.parse(notes);
console.table(mydata);
