var chakra={
"root":{
    "shape":"",
    "god":"",
    "vijmantra":"Lam लँ",
    "experiences":"",
    "color":"Red",
    "sanskrit_name":"muldhara मुलधारा",
    "location":"Base of spine",
    "glands":"Adrenaline",
    "elements":"Earth",
    "sense":"Smell",
    "Spice":"Ginger",
    "rights":"To have",
    "frequency":"256",
    "note":"C",
    "Planets":"Saturn earth",
    "connected with":"grounding safety survival trust",
    "food":"protien and meat",
    "main purpose":"source of support"
},
"sacral":{
    "shape":"",
    "god":"",
    "vijmantra":"vam वँ",
    "experiences":"",
    "color":"Orange",
    "sanskrit_name":"स्वादिस्ठाना",
    "location":"below navel",
    "glands":"gonad",
    "elements":"water",
    "sense":"taste",
    "Spice":"",
    "rights":"to feel",
    "frequency":"288",
    "note":"D",
    "Planets":"Venus",
    "connected with":"sexuality pleasure",
    "food":"liquid",
    "main purpose":"well established"
},
"solar plexus":{
    "shape":"",
    "god":"bramha dakini",
    "vijmantra":"ram रँ",
    "experiences":"",
    "color":"Yellow",
    "sanskrit_name":"मनिपुरा",
    "location":"Navel",
    "glands":"Pancreas",
    "elements":"Fire",
    "sense":"Sight smell",
    "Spice":"",
    "rights":"to act",
    "frequency":"320",
    "note":"E",
    "Planets":"Saturn earth",
    "connected with":"",
    "food":"carbohydrate",
    "main purpose":"lustorous gem"
},
"heart":{
    "shape":"",
    "god":"",
    "vijmantra":"Yam यँ",
    "experiences":"",
    "color":"Green",
    "sanskrit_name":"अनहत",
    "location":"center of chest",
    "glands":"thymus",
    "elements":"Air",
    "sense":"Touch",
    "Spice":"",
    "rights":"to love",
    "frequency":"341.3",
    "note":"F",
    "Planets":"Jupiter",
    "connected with":"love empathy humanity",
    "food":"vegetable",
    "main purpose":"healing"
},
"throat":{
    "shape":"",
    "god":"",
    "vijmantra":"hum",
    "experiences":"",
    "color":"lightblue",
    "sanskrit_name":"विशुद्घि",
    "location":"larnyx",
    "glands":"thyroid",
    "elements":"ether",
    "sense":"hearing",
    "Spice":"",
    "rights":"to express",
    "frequency":"384",
    "note":"G",
    "Planets":"Saturn",
    "connected with":"comminucation truth inspiration",
    "food":"fruit",
    "main purpose":"purification"
},
"third eye":{
    "shape":"",
    "god":"",
    "vijmantra":"wum उँ",
    "experiences":"",
    "color":"Indigo",
    "sanskrit_name":"अज्ञ्न",
    "location":"middle of forehead",
    "glands":"pituitary",
    "elements":"none",
    "sense":"intuation",
    "Spice":"",
    "rights":"to percieve",
    "frequency":"426.7",
    "note":"A",
    "Planets":"Uranus",
    "connected with":"intuation perception fantasy",
    "food":"presentation",
    "main purpose":"command"
},
"crown":{
    "shape":"",
    "god":"",
    "vijmantra":"om",
    "experiences":"",
    "color":"Violet",
    "sanskrit_name":"सहर्स",
    "location":"top of head",
    "glands":"pineal",
    "elements":"none",
    "sense":"cosmic",
    "Spice":"",
    "rights":"to know",
    "frequency":"480",
    "note":"B",
    "Planets":"Neptune",
    "connected with":"spirtulization enlightment self realization",
    "food":"fasting",
    "main purpose":""
}
}