morse={
    left:{
        value:"e",
        left:{
            value:"i",
            left:{
                value:"s",
                left:{
                    value:"h",
                    left:{
                        value:"5",
                        left:{},
                        right:{},
                    },
                    right:{
                        value:"4",
                        left:{},
                        right:{},
                    },
                },
                right:{
                    value:"v",
                    left:{},
                    right:{
                        value:"3",
                        left:{},
                        right:{},
                    },
                },
            },
            right:{
                value:"u",
                left:{
                    value:"f",
                    left:{
                        value:"5",
                        left:{},
                        right:{},
                    },
                    right:{},
                },
                right:{
                    value:"",
                    left:{
                        value:"",
                        left:{
                            value:"?",
                            left:{},
                            right:{},
                        },
                        right:{
                            value:"_",
                            left:{},
                            right:{},
                        },
                    },
                    right:{
                        value:"2",
                        left:{},
                        right:{},
                    },
                },
            },
        },
        right:{
            value:"a",
            left:{
                value:"r",
                left:{
                    value:"l",
                    left:{},
                    right:{},
                },
                right:{
                    value:"+",
                    left:{
                        value:"",
                        left:{},
                        right:{
                            value:".",
                            left:{},
                            right:{},
                        },
                    },
                    right:{},
                },
            },
            right:{
                value:"w",
                left:{
                    value:"p",
                    left:{},
                    right:{
                        value:"",
                        left:{
                            value:"@",
                            left:{},
                            right:{},
                        },
                        right:{},
                    },
                },
                right:{
                    value:"j",
                    left:{},
                    right:{
                        value:"1",
                        left:{
                            value:"'",
                            left:{},
                            right:{},
                        },
                        right:{},
                    },
                },
            },
        },
    },
    right:{
        value:"t",
        left:{
            value:"n",
            left:{
                value:"d",
                left:{
                    value:"b",
                    left:{
                        value:"6",
                        left:{},
                        right:{},
                    },
                    right:{
                        value:"=",
                        left:{},
                        right:{},
                    },
                },
                right:{
                    value:"x",
                    left:{},
                    right:{
                        value:"",
                        left:{},
                        right:{},
                    },
                },
            },
            right:{
                value:"k",
                left:{
                    value:"c",
                    left:{
                        value:"5",
                        left:{},
                        right:{},
                    },
                    right:{
                        value:"",
                        left:{
                            value:";",
                            left:{},
                            right:{},
                        },
                        right:{},
                    },
                },
                right:{
                    value:"y",
                    left:{
                        value:"(",
                        left:{},
                        right:{
                            value:")",
                            left:{},
                            right:{},  
                        },
                    },
                    right:{
                        value:"",
                        left:{},
                        right:{},
                    },
                },
            },
        },
        right:{
            value:"m",
            left:{
                value:"g",
                left:{
                    value:"z",
                    left:{
                        value:"7",
                        left:{},
                        right:{},
                    },
                    right:{
                        value:"",
                        left:{},
                        right:{
                            value:",",
                            left:{},
                            right:{},
                        },
                    },
                },
                right:{
                    value:"q",
                    left:{},
                    right:{
                        value:"",
                        left:{},
                        right:{},
                    },
                },
            },
            right:{
                value:"o",
                left:{
                    value:"",
                    left:{
                        value:"8",
                        left:{
                            value:":",
                            left:{},
                            right:{},
                        },
                        right:{},
                    },
                    right:{},
                },
                right:{
                    value:"",
                    left:{
                        value:"9",
                        left:{},
                        right:{},
                    },
                    right:{
                        value:"0",
                        left:{},
                        right:{},
                    },
                },
            },
        },
    }
    }

